import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import GroveScene from '../src/features/grove/GroveScene';
import AnimalArt from '../src/features/quiet/AnimalArt';
import PlantArt from '../src/features/quiet/PlantArt';
import {LDB} from '../src/data/livestock';
import {fixture} from './fixture';
import '../src/index.css';
import '../src/features/quiet/quiet.css';
const zone=(id,type,name,xM,yM,wM,hM,rowCount=6)=>({id,type,name,xM,yM,wM,hM,rowCount});
const zones=[zone('home','house','Farmhouse',3,3,10,7),zone('pasture','pasture','Grazing meadow',17,2,12,10),zone('barn','barn','Animal shelter',33,2,12,10),zone('orchard','orchard','Orchard',3,15,10,17,4),zone('glass','greenhouse','Greenhouse',17,15,11,8,8),zone('veg','veg','Vegetable garden',32,16,14,8,10),zone('raised','raised','Kitchen beds',17,27,11,6,8),zone('herbs','herbs','Herb garden',32,27,8,6,6),zone('water','water','Water reserve',3,36,10,7),zone('storage','storage','Tool shed',17,37,6,5),zone('compost','compost','Compost',26,37,5,5),zone('hives','beehive','Bee garden',34,37,3,2),zone('pot','container','Patio pots',40,37,5,4,4)];
const plot=(crop,z,start,rowCount,count)=>({id:z+'-'+start,zone:z,crop,status:'planted',plantDate:'2026-01-01',observedStage:4+(start%2),plantCount:count,layout:{startRow:start,rowCount,pattern:start%2?'offset':'rows',lengthM:zones.find(a=>a.id===z).wM}});
const large={...fixture,farmW:50,farmH:46,profile:{...fixture.profile,environment:'farm'},zones,garden:{plots:[plot('Apple','orchard',1,4,20),plot('Tomato','glass',1,4,64),plot('Pepper (Sweet)','glass',5,4,64),plot('Lettuce','veg',1,4,96),plot('Carrot','veg',5,6,144),plot('Cabbage','raised',1,4,60),plot('Basil','raised',5,4,64),plot('Rosemary','herbs',1,3,45),plot('Lavender','herbs',4,3,45),plot('Strawberry','pot',1,4,40)]},livestock:{animals:[{id:'cows',type:'Cow',zone:'pasture',count:5},{id:'sheep',type:'Sheep',zone:'pasture',count:3},{id:'hens',type:'Chicken',zone:'barn',count:8},{id:'bees',type:'Bee',zone:'hives',count:3}]}};
export default function Preview(){const [data,setData]=useState(large);return <main style={{maxWidth:1000,margin:'24px auto',padding:16}}><header style={{marginBottom:20}}><h1>Farm map</h1><p>Development examples · no changes to your saved farm</p><div className="q-row"><button className="q-secondary" onClick={()=>setData(large)}>Small homestead</button><button className="q-secondary" onClick={()=>setData(fixture)}>Backyard garden</button></div></header><GroveScene data={data} setData={setData}/><h2>Species portraits</h2><div style={{display:'flex',flexWrap:'wrap',gap:20}}>{Object.keys(LDB).map(name=><figure key={name} style={{margin:0,textAlign:'center'}}><AnimalArt species={name} size={100}/><figcaption>{name}</figcaption></figure>)}</div><h2>Individual growth illustrations</h2><div style={{display:'flex',flexWrap:'wrap'}}>{['Tomato','Carrot','Lettuce','Basil'].flatMap(crop=>[1,2,3,4,5].map(stage=><figure key={crop+stage} style={{margin:8}}><PlantArt crop={crop} stage={stage} size={110}/><figcaption>{crop} · {stage}</figcaption></figure>))}</div></main>;}
createRoot(document.getElementById('root')).render(<Preview/>);
